version: '3.8'

networks:
  videogamesnet:

volumes:
  mongovideogamesdb:

services:

  # container php
  videogamesphp:
    container_name: phpvideo
    build:
      context: ./php
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    environment:
      TZ: UTC
      APP_PATH: "/var/www/symfo"
      MONGODB_URL: "mongodb://videoadmin:video2024@mongovideo:27017/games"
      MONGODB_DB: "games"
    volumes:
      - ./app:/var/www/symfo
    depends_on:
      - videogamesmongo
    networks:
      - videogamesnet

  # container web
  videogamesnginx:
    container_name: nginxvideo
    image: nginx:stable-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./app:/var/www/symfo
      - ./logs:/var/log/nginx
    depends_on:
      - videogamesphp
      - videogamesmongo
      - videogamesnode
    networks:
      - videogamesnet

  # container node
  videogamesnode:
    container_name: nodevideo
    build:
      context: ./node
    volumes:
      - ./app:/var/www/symfo
    environment:
      TZ: UTC
    depends_on:
      - videogamesmongo
    networks:
      - videogamesnet
    tty: true

  # container mongo
  videogamesmongo:
    container_name: mongovideo
    image: mongo:latest
    volumes:
      - mongovideogamesdb:/data/db
      - ./datascript:/datascript
    ports:
      - "27017:27017"
    environment:
      TZ: UTC
      MONGO_INITDB_ROOT_USERNAME: videoadmin
      MONGO_INITDB_ROOT_PASSWORD: video2024
    networks:
      - videogamesnet